{
 "title": "Nginx VTS-module based metrics example",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginx_vts_info, instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(nginx_vts_server_requests_total{instance=~\"$instance\"}, host)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(nginx_vts_upstream_response_seconds{instance=~\"$instance\"}, upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_vts_info{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "description": "Processed connections rate, measured in a time frame of 5 minutes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_vts_main_connections{instance=~\"$instance\",status=\"accepted\"}[5m])",
     "legendFormat": "{{status}}-{{instance}}"
    },
    {
     "expr": "irate(nginx_vts_main_connections{instance=~\"$instance\",status=\"handled\"}[5m])",
     "legendFormat": "{{status}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Active connections count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_main_connections{instance=~\"$instance\",status!=\"requests\",status!=\"accepted\",status!=\"handled\"}",
     "legendFormat": "{{status}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Total requests ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_vts_server_requests_total{instance=~\"$instance\",host=\"$host\"}[5m])",
     "legendFormat": "{{code}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Total requests per upstream server ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_requests_total{instance=~\"$instance\",upstream=\"$upstream\"}[60s])) by (upstream,backend)",
     "legendFormat": "{{upstream}}-{{backend}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "description": "The average of request processing times in seconds.\nAverage are currently calculated as AMM (Arithmetic Mean) over both the last 60 seconds time-frame and over the last 64 samples.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_server_request_seconds{instance=~\"$instance\",host=\"$host\"}",
     "legendFormat": "{{instance}} (AMM last 64 samples)"
    },
    {
     "expr": "scalar(increase(nginx_vts_server_request_seconds_total{instance=~\"$instance\",host=\"$host\"}[60s])) / sum by (instance) (increase(nginx_vts_server_requests_total{instance=~\"$instance\",host=\"$host\"}[60s]))",
     "legendFormat": "{{instance}} (AMM 60 sec time-frame)"
    }
   ]
  },
  {
   "title": "Upstream $upstream response time average",
   "type": "graph",
   "description": "The average of only upstream response time in seconds. The average is calculated as AMM (Arithmetic Mean) over the last 64 samples.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_vts_upstream_response_seconds{instance=~\"$instance\",upstream=\"$upstream\"} > 0) by (upstream)",
     "legendFormat": "{{ upstream }} average"
    },
    {
     "expr": "nginx_vts_upstream_response_seconds{instance=~\"$instance\",upstream=\"$upstream\"}",
     "legendFormat": "backend-{{ backend }} avg"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_bytes_total{instance=~\"$instance\",host=\"$host\",direction=\"in\"}[1m])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "rate(nginx_vts_server_bytes_total{instance=~\"$instance\",host=\"$host\",direction=\"out\"}[1m])",
     "legendFormat": "{{instance}}-{{direction}}"
    }
   ]
  }
 ]
}